version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  build_deploy_to_fargate:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          repo: memento_nginx
          tag: latest
          path: ./
          dockerfile: Dockerfile
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          aws-region: AWS_DEFAULT_REGION
          cluster-name: teddytime
          family: teddytime_web
          service-name: teddytime_web
          container-image-name-updates: "container=memento_nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/memento_nginx:latest"
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main
